// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/31/2026, 4:48:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/plugins/**/*.{js,ts,mjs}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/composables/**/*.{js,ts,mjs}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/utils/**/*.{js,ts,mjs}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/liankun.wu/Documents/Repos/Personal/MaigePack/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;